### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by arbind-ladybird** [helpscout/helpscout-api-php#257]
Hello when i am trying to fetch conversation records from helpscout page wise. Per page it contains 25 records. After getting a collection of 25 records I'm performing operation on it like getting type, status etc. as per your provided method on github. But suddenly it throws error **Rate limit exceeded**. But I'm not making more than 400 request per minute. And still getting rate limit issues. How I will handle this?

**Comment by bkuhl** [comment]
Hey @arbind-ladybird,

Are there other services on your account interacting with the API at the same time?  If so, that could be the source of the issue since all users associated with the same account count against the same minute rate limit.  [Write requests also count extra against the rate limiting](https://developer.helpscout.com/mailbox-api/overview/rate-limiting/) which also may play a role depending on what actions are being performed on those conversations.

**Comment by arbind-ladybird** [comment]
No other services are interacting with them at the same time. However I
have handled this by modifying existing rate limit handler file by pausing
the script for 15 sec when remaining rate limit is 2.

**Comment by bkuhl** [comment]
Sounds good, thanks for following up with your solution - others might find it useful.
