### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by mlboudreau** [helpscout/helpscout-api-php#295]
Thank you for taking the time to submit an issue with all the details shown below.  Our engineering team monitors issues submitted and strives to respond with 1-2 business days.

How can I check if the rate limit is about to be reached?

**Comment by miguelrs** [comment]
Hey @mlboudreau!

The Mailbox API includes some headers in the responses related to rate limits, as explained in [this doc](https://developer.helpscout.com/mailbox-api/overview/rate-limiting/). Unfortunately, this SDK does not expose those headers for you to read them in an easy way. This is a feature we haven't been asked for before, but it'd be definitely an interesting addition, and we will consider it for our roadmap 👍 

In the meanwhile, note that you can access the Response (and its headers) from the Exceptions thrown, so you could try something like this:

```
try {
    $invalidConvoId = -1;
    $response = client()->conversations()->get($invalidConvoId, new ConversationRequest());
} catch (ClientException $exception) {
    $remaining = $exception->getResponse()->getHeader('X-RateLimit-Remaining-Minute')[0];
    echo 'There are ' . $remaining . ' requests remaining...';
}
```

Obviously this is not ideal though. Probably the correct approach would be to create a new Middleware that can explore the Response (similar to the [RateLimitHandler](https://github.com/helpscout/helpscout-api-php/blob/29c246d32b513da55850e23cc77c5fe204ad7db8/src/Http/Handlers/RateLimitHandler.php) for example). Then you'd need to extend our [RestClientBuilder](https://github.com/helpscout/helpscout-api-php/blob/da2db3fb3c6f3808a74ac8fa0f3152a9203dd69d/src/Http/RestClientBuilder.php#L101-L112) to be able to register your Middleware. Finally, you'd need to create your own [ApiClientFactory](https://github.com/helpscout/helpscout-api-php/blob/be33a8a2c0b2bfee9a944fac02d1cd86a55956f9/src/ApiClientFactory.php#L20) to use the RestClientBuilder you created instead of the default. 

Hope this can help you move forward for now. Please feel free to ask any other questions you have!
