### ISSUE TITLE
Problem with getCustomer

### ISSUE THREAD

**Issue by reinos** [helpscout/helpscout-api-php#48]
Hi there,

In the api you can search on email, but with the api this is not posible because you use fields?

https://github.com/helpscout/helpscout-api-php/blob/master/src/HelpScout/ApiClient.php#L337

I think `getParams()` should have just one array like

```
 public function getCustomers($page=1, $fields=array()) {
        $params = $fields;
        $params['page'] = $page;

        return $this->getCollection(
            'customers.json', $params, 'getCustomers', '\HelpScout\model\Customer'
        );
```

**Comment by Vardkin** [comment]
Kind of a late reply but I just saw this. Anyway hope it helps.

Searching customers by email uses a different method.

Instead of using `getCustomer()` which takes the parameters: `($customerId, $fields)`, search customers by email using the `searchCustomersByEmail($email, $page=1, $fields=null)` method.


[https://github.com/helpscout/helpscout-api-php/blob/master/src/HelpScout/ApiClient.php#L376](https://github.com/helpscout/helpscout-api-php/blob/master/src/HelpScout/ApiClient.php#L376)

**Comment by davidstanley01** [comment]
Closing as it looks like your issue has been resolved. Happy to re-open and help if needed.
