### ISSUE TITLE
Automatically attempt to refresh token on 400 response

### ISSUE THREAD

**Issue by davidstanley01** [helpscout/helpscout-api-php#76]
Targeting v2...

An API call where the token has expired should attempt a refresh, then try the request again.

Without making the `Authenticator` class too clumsy... might make sense to move that class to be a middleware/request handler and then the refresh check/fetch could be a response handler. Would be a fair bit of work

**Comment by scr4bble** [comment]
I would really appreciate this feature.
So now it is necessary to force the refresh manually even in case, refresh token is present in `Authenticator` object while doing the API call?

**Comment by scr4bble** [comment]
Just an observation, nobody is probably going to reuse access tokens if they are not refreshed automatically in the background (in webapps) - unless it is time critical.

**Comment by scr4bble** [comment]
While making this renewal automatic, it would be also great if it is possible to "register" a function into the client that will be called when new tokens are fetched so application can store them into database.

This would be useful also in case of half-manual refresh of tokens (current implementation), because it doesn't know when token renewal happens (tokens are not fetched when ApiClient object is being created, but with the next method called - that means it can happen at many places).

**Comment by bkuhl** [comment]
You bring up some great points, thanks for sharing that perspective.  This does seem like a pain point.  While I can't offer an ETA on this functionality, I've added it to our internal backlog.

**Comment by levu42** [comment]
@bkuhl Do you have any ETA by any chance?

**Comment by bkuhl** [comment]
No ETA yet, but I've given it a nudge :)

**Comment by bkuhl** [comment]
@levu42 @scr4bble Thanks for your patience! We've just released the ability to automatically refresh a token when it's expired.  This functionality will detect when there's an auth issue, refresh the token and retry the original request internally.  As @scr4bble mentioned, there's a callback option where you can register a closure or an object to tap into the new token once it's generated.

This is available in both [v2.7.0](https://github.com/helpscout/helpscout-api-php/releases/tag/2.7.0) and [v3.2.0](https://github.com/helpscout/helpscout-api-php/releases/tag/3.2.0)

**Comment by davidstanley01** [comment]
Nice work @bkuhl
