### ISSUE TITLE
Hydrate Conversation from Webhook Message in 2.0.3

### ISSUE THREAD

**Issue by jswinborne** [helpscout/helpscout-api-php#95]
When receiving an Event Webhook request from Helpscout, should we be able to call hydrate the conversation that is sent in JSON?

There are several bugs that cause Hydrate to error out.  The first one I noticed is on Conversation.php line 172.  There is an attempt to set an array where you need an int on threadCount. 
$this->setThreadCount($data['threads'] ?? null);
should be
$this->setThreadCount($data['threadCount'] ?? null);
or
$this->setThreadCount(count($data['threads']) ?? null);

Another issue is trying to hydrate a tag with a string, instead of an array, from the Webhook message.

**Comment by bkuhl** [comment]
Hey Jeremy,

Inflating the entities with webhook data isn't something we ensured we supported when building the SDK so it may or may not work in different scenarios.

Inflating we assume it's the count because when listing or getting conversations the [thread count is provided in the `threads` attribute](https://developer.helpscout.com/mailbox-api/endpoints/conversations/list/#response), but when creating a conversation [`threads` is actually a collection of threads](https://developer.helpscout.com/mailbox-api/endpoints/conversations/create/#request).

The inflation should probably be updated so that if `threads` is an integer it knows it's the count and if it's an array it inflates the thread collection.  We'd very much welcome a pull request to handle that as well as the tags issue you're describing.

Ideally the api wouldn't use the same attribute with multiple data types/purposes depending on the scenario.

**Comment by bkuhl** [comment]
The underlying need here is to address https://github.com/helpscout/helpscout-api-php/issues/121

**Comment by aclight** [comment]
I think I'm running into the same problem. If I use the following webhook on my server, when HelpScout  makes the call to my webhook, the `$conversation = $webhook->getConversation();` line gives an error.

```
<?php

require_once 'vendor/autoload.php';
require_once './HelpScoutConfig.php';

use HelpScout\Api\ApiClientFactory;
use HelpScout\Api\Webhooks\IncomingWebhook;

try {
	$webhook = IncomingWebhook::makeFromGlobals($GLOBALS['WebhookSecretKey']);	// This will throw an exception if the signature is not valid.

	$eventType = $webhook->getEventType();
	$conversation = null;
	switch($eventType) {
		case 'convo.created':                       // Fall through
		case 'convo.customer.reply.created':        // Fall through
		case 'convo.agent.reply.created':
			$conversation = $webhook->getConversation();
			break;
	}
}
catch (Exception $e) {
}
```
It seems that calling $webhook->getConversation() is expected to work in this situation.

I'm using the latest from the master helpscout branch.

**Comment by bkuhl** [comment]
Just wanted to give you both a head's up that this is actively being worked on.

**Comment by bkuhl** [comment]
Resolved with https://github.com/helpscout/helpscout-api-php/releases/tag/2.2.2
